 SELECT DISTINCT NOMPIL FROM PILOTE

(SELECT VILLE_DEP from  VOL ) union (SELECT VILLE_ARR from  VOL)

(SELECT VILLE_DEP from  VOL ) INTERSECT (SELECT VILLE_ARR from  VOL)

(SELECT VILLE_DEP from  VOL ) EXCEPT (SELECT VILLE_ARR from  VOL)

 SELECT NUMAV from avion where CAPAVITE > 350

 SELECT NUMAV from avion where CAPAVITE > 350

 SELECT NUMAV, NOMAV FROM AVION WHERE LOC = 'Nice';

 SELECT NUMPIL, VILLE_DEP FROM VOL 

SELECT NOMPIL FROM PILOTE WHERE ADR = 'Paris' AND SAL > 2500;

SELECT DISTINCT A.NUMPIL, A.NOMPIL, B.NUMPIL, B.NOMPIL
FROM PILOTE A, PILOTE B
WHERE A.NOMPIL = B.NOMPIL AND A.NUMPIL != B.NUMPIL;

SELECT NUMPIL FROM PILOTE WHERE NUMPIL NOT IN
(SELECT NUMPIL FROM VOL WHERE H_DEP IS NOT NULL)

SELECT NUMVOL, VILLE_DEP FROM VOL WHERE NUMPIL IN (100, 204)

SELECT NUMPIL FROM PILOTE INNERJOIN VOLE ON PILOTE.NOMPIL==VOLE.NOMPIL
WHERE PILOTE.NOMPIL != 'Durand' 

SELECT NUMVOL FROM PILOTE INNERJOIN VOLE ON PILOTE.NOMPIL==VOLE.NOMPIL
WHERE VILLE_DEP = 'Nice' AND P.ADR = 'Nice' 

SELECT NUMVOL FROM VOL
WHERE NUMAV NOT IN (SELECT NUMAV FROM AVION WHERE LOC = 'Nice');

 SELECT P.NUMPIL, P.NOMPIL FROM PILOTE P, VOL V, AVION A
WHERE P.NUMPIL = V.NUMPIL AND V.NUMAV = A.NUMAV AND A.CAPACITE > 300
AND V.VILLE_DEP = 'Nice';

SELECT DISTINCT P.NOMPIL FROM PILOTE P, VOL V, AVION A
WHERE P.ADR = 'Paris' AND V.VILLE_DEP = 'Nice' AND A.NOMAV = 'Airbus A380'
AND V.NUMPIL = P.NUMPIL AND V.NUMAV = A.NUMAV;

SELECT SELECT NUMVOL FROM PILOTE INNERJOIN VOLE ON PILOTE.NOMPIL==VOLE.NOMPIL INNERJOIN AVION ON VOL.NOMAV == AVION.NOMAV
WHERE ( PILOTE.NOMPIL = 'Nices' OU VILLE_ARR ="Nice" ) AND AVION.LOC='paris'

SELECT NUMPIL, NOMPIL FROM PILOTE WHERE ADR = (SELECT ADR FROM PILOTE WHERE NOMPIL = 'Dupont');

SELECT NUMPIL FROM  PILOTE INNERJOIN VOLE ON PILOTE.NOMPIL==VOLE.NOMPIL
WHERE VOLE.VOL_DEP = PILOTE.ADR




